# Базовый образ: лёгкий Python 3.12
FROM python:3.12-slim
 

WORKDIR /app
 

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
 

COPY . .
 

CMD python seed.py && uvicorn main:app --host 0.0.0.0 --port 8000
 